stages:
  - build

.build_template:
  stage: build
  image:
    # Use CERN version of the Kaniko image
    name: gitlab-registry.cern.ch/ci-tools/docker-image-builder
    entrypoint: [""]
  variables:
    DOCKERFILE: <Dockerfile path>
    VERSION: devel
    OSTAG: <Tag suffix corresponding to version>
    # Use single quotes to escape colon
    DESTINATION: '${CI_REGISTRY_IMAGE}/${IMAGE}:${VERSION}-${OSTAG}'
  before_script:
    # Prepare Kaniko configuration file
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - printenv
    # Build and push the image from the given Dockerfile
    # See https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#variables-reference for available variables
    - /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile ${DOCKERFILE}
      --build-arg REPOSITORY=${CI_REGISTRY_IMAGE}
      --build-arg VERSION=${VERSION}
      --destination ${DESTINATION}
    - echo /kaniko/executor --context $CI_PROJECT_DIR
      --dockerfile ${DOCKERFILE}
      --build-arg REPOSITORY=${CI_REGISTRY_IMAGE}
      --build-arg VERSION=${VERSION}
      --destination ${DESTINATION}
  # only:
  #   # Only build if the generating files change
  #   changes:
  #     - ${DOCKERFILE}

build-environment:
  extends: .build_template
  variables:
    DOCKERFILE: AlmaLinux9/Dockerfile-environment
    IMAGE: mucoll-environment
    OSTAG: el9

build-spack:
  extends: .build_template
  variables:
    DOCKERFILE: AlmaLinux9/Dockerfile-spack
    IMAGE: mucoll-spack
    OSTAG: el9
  needs: [build-environment]

build-sim:
  extends: .build_template
  variables:
    DOCKERFILE: AlmaLinux9/Dockerfile
    IMAGE: mucoll-sim
    OSTAG: el9
  needs: [build-spack]