###############################################################################
#  Repository: mucoll-pynb
#  Tag:        1.8-almalinux9
###############################################################################

FROM almalinux:9.2

RUN yum -y install epel-release yum-utils wget && \
    yum-config-manager --set-enabled appstream crb extras plus && \
    yum -y update

RUN wget -O /etc/yum.repos.d/geant4.repo https://nexus.pd.infn.it/artifacts/repository/repo-files/geant4.repo && \
    wget -O /etc/yum.repos.d/mc-key4hep.repo https://nexus.pd.infn.it/artifacts/repository/repo-files/mc-key4hep.repo

RUN yum -y install muonc-base-installation podio python3-podio python3-podio-utils edm4hep \
                   gaudi gaudi-tools python3-gaudi key4hep-edm4hep2lcio key4hep-fw-core \
                   key4hep-lcio-reader key4hep-marlin-wrapper python3-k4marlin-wrapper \
                   python3-pip python3-jupyroot && \
    geant4-dataset-download && \
    pip3 install jupyter

RUN useradd -u 1000 almalinux

USER almalinux

RUN mkdir /home/almalinux/.jupyter /home/almalinux/workarea

COPY jupyter_notebook_config.py /home/almalinux/.jupyter

