###############################################################################
#  Repository: ${REPOSITORY}/mucoll-sim
#  Tag:        ${VERSION}-alma9
###############################################################################

ARG VERSION=dev
ARG REPOSITORY=madbaron
FROM ${REPOSITORY}/mucoll-minimal:${VERSION}-alma9

# Adding repository: MuColl
ARG MUCOLL_COMMIT=11a32828ca9230337562dc43f91a25862d3a21ff

RUN source /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/mucoll-spack && \
    git clone https://github.com/madbaron/mucoll-spack ${REPOPATH} && \
    if [ -n "${MUCOLL_COMMIT}" ]; then \
      cd ${REPOPATH}; \
      git checkout ${MUCOLL_COMMIT}; \
    fi

# Apply our patches to spack
COPY apply_patches.sh ./apply_patches.sh

RUN source /opt/setup_spack.sh && \
    ./apply_patches.sh ${SPACK_ROOT}/var/mucoll-spack

# Add the package repositories
RUN source /opt/setup_spack.sh && \
    spack repo add --scope system ${SPACK_ROOT}/var/mucoll-spack

# Create the release environment
RUN source /opt/setup_spack.sh && \
    cd ${SPACK_ROOT}/var/mucoll-spack/environments/mucoll-release && \
    spack env activate . && \
    cd - && \
    echo "source /opt/setup_spack.sh" > ${HOME}/setup_env.sh && \
    echo "cd ${SPACK_ROOT}/var/mucoll-spack/environments/mucoll-release" >> ${HOME}/setup_env.sh && \
    echo "spack env activate ." >> ${HOME}/setup_env.sh && \
    echo "cd -" >> ${HOME}/setup_env.sh && \
    echo "spack env status" >> ${HOME}/setup_env.sh

# Concretizing the MuColl stack reusing system packages as external
RUN source ${HOME}/setup_env.sh && \
    spack add mucoll-stack && \
    spack concretize --reuse

# Installing fragments of dependency tree in separate layers for cached debugging
ENV SPACK_INSTALL_OPTS="--only-concrete --no-add --fail-fast"

RUN source ${HOME}/setup_env.sh && \
    spack spec -NIt && \
    spack install ${SPACK_INSTALL_OPTS} && \
    spack clean -a

RUN source ${HOME}/setup_env.sh && \
    echo "source ${SPACK_ENV}/.spack-env/view/setup.sh" > /opt/setup_mucoll.sh && \
    echo "alias setup_mucoll=\"source /opt/setup_mucoll.sh\"" >> /etc/profile.d/aliases.sh

# Setting up users to be used for the local environment setup
RUN useradd --shell /bin/bash --create-home mucoll
USER mucoll
WORKDIR /home/mucoll

ENTRYPOINT ["/bin/bash", "--login"]

