###############################################################################
#  Repository: ${REPOSITORY}/mucoll-environment
#  Tag:        ${VERSION}-el9
###############################################################################

ARG VERSION=release
ARG REPOSITORY=infnpd
FROM cern/alma9-base:latest

# Installing updates required for Spack
RUN yum update -y && \
    yum install -y epel-release && \
    yum update -y

RUN yum --enablerepo epel groupinstall -y "Development Tools" && \
    yum --enablerepo epel install -y tmux vim curl findutils gcc-gfortran git gnupg2 hostname iproute python3 python3-pip python3-setuptools unzip
RUN python3 -m pip install boto3

# Installing additional components for use by Spack as external packages
RUN yum --enablerepo epel install -y cmake gettext ninja-build texinfo
