###############################################################################
#  Repository: mucoll-spack
#  Tag:        ${VERSION}-alma9
###############################################################################

ARG VERSION=release
ARG REPOSITORY=infnpd
FROM gitlab-registry.cern.ch/key4hep/k4-deploy/alma9-build

# Adding repositories: Spack
ARG SPACK_COMMIT=57b83e5fb29ae3c84cf81eb0ed89c83e49dd3217

# Setting up Spack
RUN git clone https://github.com/spack/spack.git /opt/spack && \
    echo "source /opt/spack/share/spack/setup-env.sh" >> /opt/setup_spack.sh && \
    echo "alias setup_spack=\"source /opt/setup_spack.sh\"" >> /etc/profile.d/aliases.sh

# Using specific commit of Key4hep repository if requested
RUN if [ -n "${SPACK_COMMIT}" ]; then \
      cd /opt/spack; \
      git checkout ${SPACK_COMMIT}; \
    fi

# Registering compilers with Spack
ENV SPACK_COLOR="always"
RUN source /opt/setup_spack.sh && \
    spack compiler find
