###############################################################################
#  Repository: mucoll-ilc-base
#  Tag:        1.7-almalinux9
###############################################################################

FROM infnpd/mucoll-environment:1.7-almalinux9

RUN cd /opt && git clone https://github.com/MuonColliderSoft/MuonCutil.git && \
    git clone https://github.com/MuonColliderSoft/iLCInstall.git && \
    cd /opt/MuonCutil && git checkout v02-08-MC && \
    cd /opt/iLCInstall && git checkout ILCSoft2.3.1 && \
    ln -sf /opt/MuonCutil/releases/v02-08-MC releases && \
    ./ilcsoft-install releases/v02-08-MC/release-base.cfg --install-prefix=/opt/ilcsoft -v -i


