###############################################################################
#  Repository: ${REPOSITORY}/mucoll-sim
#  Tag:        ${VERSION}-el9
###############################################################################

ARG VERSION=release
ARG REPOSITORY=infnpd
FROM ${REPOSITORY}/mucoll-spack:${VERSION}-el9

# Adding repositories: Key4hep + MuColl
ARG KEY4HEP_COMMIT=354e3ce1e2c284c6516e34b60d2934e894078be2
ARG MUCOLL_COMMIT=5e040f4e2c4200c0f62061cbef02ee83b6208cb2

RUN source /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/spack/repos/key4hep-spack && \
    git clone https://github.com/key4hep/key4hep-spack ${REPOPATH} && \
    if [ -n "${KEY4HEP_COMMIT}" ]; then \
      cd ${REPOPATH}; \
      git checkout ${KEY4HEP_COMMIT}; \
    fi

RUN source /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/spack/repos/mucoll-spack && \
    git clone https://github.com/MuonColliderSoft/mucoll-spack ${REPOPATH} && \
    if [ -n "${MUCOLL_COMMIT}" ]; then \
      cd ${REPOPATH}; \
      git checkout ${MUCOLL_COMMIT}; \
    fi

# Apply patches to spack :shrug:
RUN source /opt/setup_spack.sh && \
    cd ${SPACK_ROOT} && \
    source ${SPACK_ROOT}/var/spack/repos/key4hep-spack/.cherry-pick

# Add the package repositories
RUN source /opt/setup_spack.sh && \
    spack repo add --scope system ${SPACK_ROOT}/var/spack/repos/key4hep-spack && \
    spack repo add --scope system ${SPACK_ROOT}/var/spack/repos/mucoll-spack

# Create the release environment
RUN source /opt/setup_spack.sh && \
    echo "Creating the release environment... ${PWD}" &&\
    spack env create sim && \
    spack env activate sim && \
    echo "Post environment activation... ${PWD}" &&\
    cp ${SPACK_ROOT}/var/spack/repos/mucoll-spack/environments/mucoll-release/*.yaml ${SPACK_ENV} && \
    echo "source /opt/setup_spack.sh" > ${HOME}/setup_env.sh && \
    echo "echo \"Spack activated. \${PWD}\"" >> ${HOME}/setup_env.sh && \
    echo "spack env activate sim" >> ${HOME}/setup_env.sh && \
    echo "spack env status" >> ${HOME}/setup_env.sh

# Concretizing the MuColl stack reusing system packages as external
RUN echo ${HOME}/setup_env.sh && cat ${HOME}/setup_env.sh && source ${HOME}/setup_env.sh && \
    spack concretize --reuse

# Installing fragments of dependency tree in separate layers for cached debugging
ENV SPACK_INSTALL_OPTS "--only-concrete --no-add --fail-fast"

RUN source ${HOME}/setup_env.sh && \
    spack spec -NIt root && \
    spack install ${SPACK_INSTALL_OPTS} root && \
    spack clean -a
RUN source ${HOME}/setup_env.sh && \
    spack spec -NIt dd4hep && \
    spack install ${SPACK_INSTALL_OPTS} dd4hep && \
    spack clean -a
RUN source ${HOME}/setup_env.sh && \
    spack spec -NIt && \
    spack install ${SPACK_INSTALL_OPTS} && \
    spack clean -a

RUN source ${HOME}/setup_env.sh && \
    echo "source ${MUCOLL_STACK}" > /opt/setup_mucoll.sh && \
    echo "alias setup_mucoll=\"source /opt/setup_mucoll.sh\"" >> /etc/profile.d/aliases.sh

# Setting up users to be used for the local environment setup
RUN useradd --shell /bin/bash --create-home mucoll
USER mucoll
WORKDIR /home/mucoll

ENTRYPOINT ["/bin/bash", "--login"]

