###############################################################################
#  Repository: mucoll-environment
#  Tag:        2.0-el9
###############################################################################

FROM cern/alma9-base:latest

# Installing updates required for Spack
RUN yum update -y && \
    yum install -y epel-release && \
    yum update -y

RUN yum --enablerepo epel groupinstall -y "Development Tools" && \
    yum --enablerepo epel install -y tmux passwd vim curl findutils gcc-c++ gcc gcc-gfortran git gnupg2 hostname iproute make patch python3 python3-pip python3-setuptools unzip
RUN python3 -m pip install boto3

# Installing newer GCC compiler
RUN yum --enablerepo epel install -y gcc-toolset-12

# Installing additional components for use by Spack as external packages
RUN yum --enablerepo epel install -y cmake gettext ninja-build

# Setting up users to be used for the local environment setup
RUN echo "root" | passwd --stdin root
RUN useradd --shell /bin/bash --create-home sim && \
    echo "sim" | passwd --stdin sim
USER sim
WORKDIR /home/sim

