###############################################################################
#  Repository: mucoll-minimal
#  Tag:        2.9-almalinux9
###############################################################################

FROM almalinux:9.4

RUN yum -y install epel-release wget yum-utils && \
    yum-config-manager --set-enabled appstream crb extras plus && \
    wget -O /etc/yum.repos.d/geant4.repo https://nexus.pd.infn.it/artifacts/repository/repo-files/geant4.repo && \
    wget -O /etc/yum.repos.d/mc-key4hep.repo https://nexus.pd.infn.it/artifacts/repository/repo-files/mc-key4hep.repo && \
    yum -y install muonc-base-installation key4hep-marlin-wrapper python3-k4fwcore && \
    geant4-dataset-download

#TODO publish according to https://awesome-workshop.github.io/docker-cms/06-unpacked/index.html

