###############################################################################
#  Repository: mucoll-ilc-base
#  Tag:        1.5-centos8
###############################################################################

FROM infnpd/mucoll-environment:1.5-centos8

RUN cd /opt && git clone https://github.com/MuonColliderSoft/MuonCutil.git && \
    git clone https://github.com/iLCSoft/iLCInstall.git && \
    cd /opt/MuonCutil && git checkout a01c1660da963d4b7cb299b1dd0e1f0c52164b18 && \
    cd /opt/iLCInstall && git checkout v02-02 && \
    sed -i 's|/usr/bin/env python|/usr/bin/env python2|g' ilcsoft-install && \
    mkdir releases/development && \
    cp /opt/MuonCutil/releases/development/* releases/development && \
    ./ilcsoft-install releases/development/release-base.cfg --install-prefix=/opt/ilcsoft -v -i


