###############################################################################
#  Repository: mucoll-spack
#  Tag:        ${VERSION}-cs8stream
###############################################################################

ARG VERSION=release
ARG REPOSITORY=infnpd
FROM ${REPOSITORY}/mucoll-environment:${VERSION}-cs8stream

# Adding repositories: Spack
ARG SPACK_COMMIT=f5946c4621035dd466953c8d2664ff5f82f38138

# Setting up Spack
RUN git clone https://github.com/spack/spack.git /opt/spack && \
    echo "source /opt/rh/gcc-toolset-11/enable" >> /opt/setup_spack.sh && \
    echo "source /opt/spack/share/spack/setup-env.sh" >> /opt/setup_spack.sh && \
    echo "alias setup_spack=\"source /opt/setup_spack.sh\"" >> /etc/profile.d/aliases.sh

# Using specific commit of Key4hep repository if requested
RUN if [ -n "${SPACK_COMMIT}" ]; then \
      cd /opt/spack; \
      git checkout ${SPACK_COMMIT}; \
    fi

# Registering compilers with Spack
ENV SPACK_COLOR="always"
RUN source /opt/setup_spack.sh && \
    spack compiler find && \
    spack compilers && \
    spack spec cmake

# Enabling use of LD_LIBRARY - required for proper run-environment setup
RUN source /opt/setup_spack.sh && \
    spack config add modules:prefix_inspections:lib64:[LD_LIBRARY_PATH] && \
    spack config add modules:prefix_inspections:lib:[LD_LIBRARY_PATH]
# Adding system build packages as external (to speed up installation)
RUN source /opt/setup_spack.sh && \
    spack external find
