###############################################################################
#  Repository: mucoll-ilc-framework
#  Tag:        1.6-centos8stream
###############################################################################

FROM infnpd/mucoll-ilc-base:1.6-centos8stream

RUN cd /opt/iLCInstall && \
    ./ilcsoft-install releases/development/release-ilcsoft.cfg --install-prefix=/opt/ilcsoft -v -i

RUN cd /opt/ilcsoft/muonc && \
    git clone https://github.com/MuonColliderSoft/detector-simulation.git && \
    cd /opt/ilcsoft/muonc/detector-simulation && git checkout v01-02-MC

RUN sed -i -e 's|/bin/env python|/usr/bin/env python2|g' /opt/ilcsoft/muonc/CEDViewer/*/bin/ced2go

COPY profile.d_ilcsoft.sh /etc/profile.d/ilcsoft.sh
