###############################################################################
#  Repository: ${REPOSITORY}/mucoll-environment
#  Tag:        ${VERSION}-cs8stream
###############################################################################

ARG VERSION=devel
ARG REPOSITORY=infnpd
FROM cern/c8-base:latest

# Installing updates required for Spack
RUN yum update -y && \
    yum install -y epel-release && \
    yum update -y

RUN yum --enablerepo epel groupinstall -y "Development Tools" && \
    yum --enablerepo epel install -y tmux vim curl findutils gcc-gfortran git gnupg2 hostname iproute redhat-lsb-core python3 python3-pip python3-setuptools unzip
RUN python3 -m pip install boto3

# Installing newer GCC compiler
RUN yum --enablerepo epel install -y gcc-toolset-11
