###############################################################################
#  Repository: mucoll-ilc-framework
#  Tag:        1.3-centos8
###############################################################################

FROM infnpd/mucoll-ilc-base:1.3-centos8

RUN cd /opt/iLCInstall && \
    ./ilcsoft-install releases/development/release-ilcsoft.cfg --install-prefix=/opt/ilcsoft -v -i

RUN cd /opt/ilcsoft/v02-04-MC && \
    git clone https://github.com/MuonColliderSoft/detector-simulation.git && \
    cd /opt/ilcsoft/v02-04-MC/detector-simulation && git checkout v01-00-MC

RUN sed -i 's|/bin/env python|/usr/bin/env python2|g' /opt/ilcsoft/v02-04-MC/CEDViewer/v01-17-01/bin/ced2go

COPY profile.d_ilcsoft.sh /etc/profile.d/ilcsoft.sh

RUN sed -i -e 's|:\$MARLIN_DLL||g' /opt/ilcsoft/v02-04-MC/init_ilcsoft.sh

