###############################################################################
#  Repository: mucoll-ilc-base
#  Tag:        1.6-centos8
###############################################################################

FROM infnpd/mucoll-environment:1.6-centos8

RUN cd /opt && git clone https://github.com/MuonColliderSoft/MuonCutil.git && \
    git clone https://github.com/MuonColliderSoft/iLCInstall.git && \
    cd /opt/MuonCutil && git checkout v02-07-MC && \
    cd /opt/iLCInstall && git checkout v02-03-01-MC && \
    mkdir releases/development && \
    cp /opt/MuonCutil/releases/development/* releases/development && \
    ./ilcsoft-install releases/development/release-base.cfg --install-prefix=/opt/ilcsoft -v -i


