###############################################################################
#  Repository: mucoll-ilc-framework
#  Tag:        1.5-centos8
###############################################################################

FROM infnpd/mucoll-ilc-base:1.5-centos8

RUN cd /opt/iLCInstall && \
    ./ilcsoft-install releases/development/release-ilcsoft.cfg --install-prefix=/opt/ilcsoft -v -i

RUN cd /opt/ilcsoft/muonc && \
    git clone https://github.com/MuonColliderSoft/detector-simulation.git && \
    cd /opt/ilcsoft/muonc/detector-simulation && git checkout v01-01-MC

RUN sed -i -e 's|/bin/env python|/usr/bin/env python2|g' /opt/ilcsoft/muonc/CEDViewer/*/bin/ced2go

COPY profile.d_ilcsoft.sh /etc/profile.d/ilcsoft.sh

RUN sed -i -e 's|:\$MARLIN_DLL||g' /opt/ilcsoft/muonc/init_ilcsoft.sh


