name: build-image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push mucoll-environment
        id: docker_build_mucoll-environment
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-environment
          tags: kkrizka/mucoll-environment:${{github.sha}}
      -
        name: Build and push mucoll-ilc-base
        id: docker_build_mucoll-ilc-base
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-environment
          build-args: |
            TAG=${{github.sha}}
          tags: kkrizka/mucoll-ilc-base:${{github.sha}}
      -
        name: Build and push mucoll-ilc-framework
        id: docker_build_mucoll-ilc-framework
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-environment
          build-args: |
            TAG=${{github.sha}}
          tags: kkrizka/mucoll-ilc-framework:${{github.sha}}