name: build-image
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'key4hep'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-dummy
      -
        name: Build and Push (mucoll-environment)
        id: docker_build_mucoll-environment
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./AlmaLinux9
          file: ./AlmaLinux9/Dockerfile-environment
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-environment:${{steps.meta.outputs.version}}-alma9
      -
        name: Build and Push (mucoll-spack)
        id: docker_build_mucoll-spack
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./AlmaLinux9
          file: ./AlmaLinux9/Dockerfile-spack
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-spack:${{steps.meta.outputs.version}}-alma9
      -
        name: Build and Push (mucoll-sim)
        id: docker_build_mucoll-sim
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./AlmaLinux9
          file: ./AlmaLinux9/Dockerfile-sim
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-sim:${{steps.meta.outputs.version}}-alma9
