name: build-image
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'key4hep*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 720
    strategy:
      matrix:
        os: [{dir: AlmaLinux9,suffix: alma9}]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: lowercase repository name
        run: |
            echo "REPONAME={${{ github.repository_owner }},,}" >>${GITHUB_ENV}
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${REPONAME}/mucoll-dummy
      - name: Build and Push (mucoll-spack)
        id: docker_build_mucoll-spack
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-spack
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=ghcr.io/${REPONAME}
          tags: ghcr.io/${REPONAME}/mucoll-spack:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
      - name: Build and Push (mucoll-sim)
        id: docker_build_mucoll-sim
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-sim
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=ghcr.io/${REPONAME}
          tags: ghcr.io/${REPONAME}/mucoll-sim:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
