name: build-image
on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'main'
jobs:
  centos8:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-dummy
      -
        name: Build and Push (mucoll-environment)
        id: docker_build_mucoll-environment
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-environment
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-environment:${{steps.meta.outputs.version}}-centos8
      -
        name: Build and Push (mucoll-ilc-base)
        id: docker_build_mucoll-ilc-base
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-ilc-base
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-ilc-base:${{steps.meta.outputs.version}}-centos8
      -
        name: Build and Push (mucoll-ilc-framework)
        id: docker_build_mucoll-ilc-framework
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-ilc-framework
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-ilc-framework:${{steps.meta.outputs.version}}-centos8
  alma9:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-dummy
      -
        name: Build and Push (mucoll-environment)
        id: docker_build_mucoll-environment
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./AlmaLinux9
          file: ./AlmaLinux9/Dockerfile-environment
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-environment:${{steps.meta.outputs.version}}-alma9
      -
        name: Build and Push (mucoll-ilc-base)
        id: docker_build_mucoll-ilc-base
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./AlmaLinux9
          file: ./AlmaLinux9/Dockerfile-ilc-base
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-ilc-base:${{steps.meta.outputs.version}}-alma9
      -
        name: Build and Push (mucoll-ilc-framework)
        id: docker_build_mucoll-ilc-framework
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./AlmaLinux9
          file: ./AlmaLinux9/Dockerfile-ilc-framework
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-ilc-framework:${{steps.meta.outputs.version}}-alma9
