name: build-image
on: push
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Meta (mucoll-environment)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-environment
      -
        name: Build and Push (mucoll-environment)
        id: docker_build_mucoll-environment
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-environment
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build and push mucoll-ilc-base
        id: docker_build_mucoll-ilc-base
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-ilc-base
          build-args: |
            TAG=${{github.sha}}
          tags: ${{secrets.DOCKERHUB_REPOSITORY}}/mucoll-ilc-base:${{github.sha}}
      -
        name: Build and push mucoll-ilc-framework
        id: docker_build_mucoll-ilc-framework
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./CentOS8
          file: ./CentOS8/Dockerfile-ilc-framework
          build-args: |
            TAG=${{github.sha}}
          tags: ${{secrets.DOCKERHUB_REPOSITORY}}/mucoll-ilc-framework:${{github.sha}}