name: build-image
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'key4hep'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [{dir: CentOS8,suffix: cs8stream}, {dir: AlmaLinux9,suffix: el9}]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-dummy
      -
        name: Build and Push (mucoll-environment)
        id: docker_build_mucoll-environment
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-environment
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-environment:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
      -
        name: Build and Push (mucoll-spack)
        id: docker_build_mucoll-spack
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-spack
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-spack:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
      -
        name: Build and Push (mucoll-sim)
        id: docker_build_mucoll-sim
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ secrets.DOCKERHUB_REPOSITORY }}
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/mucoll-sim:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
