name: build-image
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
jobs:
  sim:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Simulate Events
        container: kkrizka/mucoll-ilc-framework:v.1.6-centos8
        run: |
          ddsim --steeringFile test/sim_steer_muonGun_MuColl_v1.py
