name: Test Marlin Processors
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
jobs:
  sim:
    runs-on: ubuntu-latest
    container: kkrizka/mucoll-ilc-framework:v.1.6-centos8
    steps:
      -
        id: cache-sim
        name: Prepare event simulation cache
        uses: actions/cache@v2
        with:
          path: muonGun_sim_MuColl_v1.slcio
          key: events-${{ hashFiles('muonGun_sim_MuColl_v1.slcio') }}
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Simulate Events
        if: steps.cache-sim.outputs.cache-hit != 'true'
        run: |
          source /opt/ilcsoft/muonc/init_ilcsoft.sh
          echo $PATH | tr : '\n'
          ls /opt/ilcsoft/muonc/DD4hep/v01-16/bin
          which ddsim
          export
          ddsim --steeringFile test/sim_steer_muonGun_MuColl_v1.py
  proc-ACTSTracking:
    needs: sim
    runs-on: ubuntu-latest
    container: kkrizka/mucoll-ilc-framework:v.1.6-centos8
    steps:
      -
        id: cache-sim
        name: Get simulated events from cache
        uses: actions/cache@v2
        with:
          path: muonGun_sim_MuColl_v1.slcio
          key: events-${{ hashFiles('muonGun_sim_MuColl_v1.slcio') }}
      -
        name: Run ACTSTracking example
        run: |
          source /opt/ilcsoft/muonc/init_ilcsoft.sh
          ls
          Marlin /opt/ilcsoft/muonc/ACTSTracking/main/example/actsseedckf_seed0_steer.xml --global.LCIOInputFiles=muonGun_sim_MuColl_v1.slcio